feat: optimized hexadecimal to string conversion
shadow-hq/shadow-reth pull request #10
Opened 2024-05-24 15:48 UTC by malik672

The PR optimizes the ToLowerHex trait implementations for types (B256, Address, B64, Bloom, Bytes) by pre-allocating string memory and using the write! macro for direct formatting, significantly reducing memory allocations and improving performance.

2024-05-24 19:21 UTC, Jon-Becker requested changes
thank you for contributing!!

do you have benchmarks anywhere? im curious if this is actually faster / more efficient since we're initializing a string, and it should allocate just enough memory for the string

2024-05-24 19:21 UTC, Jon-Becker commented on crates/common/src/db.rs
> +    ) -> Result<(), sqlx::Error> {///ERRRRRRRRROROROORROORROROROROOROROR
remove

2024-05-25 10:08 UTC, malik672 commented
> thank you for contributing!!
> 
> do you have benchmarks anywhere? im curious if this is actually faster / more efficient since we're initializing a string, and it should allocate just enough memory for the string

nah, but will do one now, yeah it should be more efficient than using the format! macro which reallocates based on if initial capacity is exceeded

2024-05-25 10:09 UTC, malik672 commented on crates/common/src/db.rs
> +    ) -> Result<(), sqlx::Error> {///ERRRRRRRRROROROORROORROROROROOROROR
lmaoo, how did i skip this

2024-05-25 15:56 UTC, malik672 commented
well i ran the benchmark and the format was fastere

2024-05-25 15:56 UTC, closed without merging

2024-05-25 19:12 UTC, Jon-Becker commented
no problem! we appreciate the contribution anyway ❤️